### ISSUE TITLE
希望能够调整一下中部的布局

### ISSUE THREAD

**Issue by JohnNiang** [cuntoulaoyangtou/halo-ctlyt-gently#1]
当我刚开始使用 halo 并使用本主题时，布局先得很突兀，希望作者能够完善一下。随后我们会考虑收录该主题到官网中。

首页情况如下：

![image](https://user-images.githubusercontent.com/16865714/74585185-edf44c80-5014-11ea-9b7b-8e7fbdbb392d.png)

**Comment by cuntoulaoyangtou** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Niang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午5:02
收件人:&nbsp;"cuntoulaoyangtou/halo-ctlyt-gently"<halo-ctlyt-gently@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cuntoulaoyangtou/halo-ctlyt-gently] 希望能够调整一下中部的布局 (#1)




当我刚开始使用 halo 并使用本主题时，布局先得很突兀，希望作者能够完善一下。随后我们会考虑收录该主题到官网中。
 
首页情况如下：
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

中部内容进行了细致的调整效果图如下：


beanner根据置顶文章显示
